
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Skeleton from '@/components/Skeleton'

const inter = Inter({ subsets: ['latin'] })

export default function contactus () {
    return (
        <>
          <Head>
            <title>Simple Quiz App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={`${styles.main} ${inter.className}`}>
    
          <div style={{width: '110%'}}><Skeleton /></div>
          </main>
        </>
      )

    }

